apiVersion: v1
kind: Service
metadata:
  name: {{ include "boundary.fullname" . }}
  labels:
    {{- include "boundary.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 9200
      targetPort: api
      protocol: TCP
      name: api
    - port: 9201
      targetPort: cluster
      protocol: TCP
      name: cluster
    - port: 9202
      targetPort: data
      protocol: TCP
      name: data
  selector:
    {{- include "boundary.selectorLabels" . | nindent 4 }}
