apiVersion: v1
kind: Service
metadata:
  name: {{ include "o-an-quan.fullname" . }}-fe
  labels:
    {{- include "o-an-quan.labels" . | nindent 4 }}
    component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "o-an-quan.selectorLabels" . | nindent 4 }}
    component: frontend