apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "conduit.fullname" . }}
  labels:
    {{- include "conduit.labels" . | nindent 4 }}
data:
  conduit.toml: |
    [global]
    # The server_name is the name of this server. It is used as a suffix for user
    # and room ids. Examples: matrix.org, conduit.rs
    # The Conduit server needs to be reachable at https://your.server.name/ on port
    # 443 (client-server) and 8448 (federation) OR you can create /.well-known
    # files to redirect requests. See
    # https://matrix.org/docs/spec/client_server/latest#get-well-known-matrix-client
    # and https://matrix.org/docs/spec/server_server/r0.1.4#get-well-known-matrix-server
    # for more information

    server_name = {{ quote .Values.conduit_toml.server_name }}

    # This is the only directory where Conduit will save its data
    database_path = {{ quote .Values.conduit_toml.database_path }}

    # The port Conduit will be running on. You need to set up a reverse proxy in
    # your web server (e.g. apache or nginx), so all requests to /_matrix on port
    # 443 and 8448 will be forwarded to the Conduit instance running on this port
    port = {{ .Values.conduit_toml.port }}

    # Max size for uploads
    max_request_size = {{ .Values.conduit_toml.max_request_size }} # in bytes

    # Enables registration. If set to false, no users can register on this server.
    allow_registration = {{ .Values.conduit_toml.allow_registration }}

    # Disable encryption, so no new encrypted rooms can be created
    # Note: existing rooms will continue to work
    #allow_encryption = false
    #allow_federation = false

    # Enable jaeger to support monitoring and troubleshooting through jaeger
    #allow_jaeger = false

    trusted_servers = {{ .Values.conduit_toml.trusted_servers }}

    #max_concurrent_requests = 100 # How many requests Conduit sends to other servers at the same time
    #log = "info,state_res=warn,rocket=off,_=off,sled=off"
    #workers = 4 # default: cpu core count * 2

    address = "127.0.0.1" # This makes sure Conduit can only be reached using the reverse proxy
    #address = "0.0.0.0" # If Conduit is running in a container, make sure the reverse proxy (ie. Traefik) can reach it.

    proxy = {{ quote .Values.conduit_toml.proxy }} # more examples can be found at src/database/proxy.rs:6

    # The total amount of memory that the database will use.
    #db_cache_capacity_mb = 200
