apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "glance.name" . }}
  labels:
    {{- include "glance.labels" . | nindent 4 }}
data:
  glance.yml: |
    {{- toYaml .Values.config | nindent 4 }}
