{{ if .Values.webhook.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "yuta.fullname" . }}-webhook
  labels:
    {{- include "yuta.labels" . | nindent 4 }}
    component: webhook
spec:
  replicas: {{ .Values.webhook.replicaCount }}
  selector:
    matchLabels:
      {{- include "yuta.selectorLabels" . | nindent 6 }}
      component: webhook
  template:
    metadata:
      {{- with .Values.webhook.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "yuta.selectorLabels" . | nindent 8 }}
        component: webhook
    spec:
      {{- with .Values.webhook.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "yuta.serviceAccountName" . }}-webhook
      securityContext:
        {{- toYaml .Values.webhook.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          command: ["/webhook"]
          args:
          - '--config'
          - '/config.yaml'
          securityContext:
            {{- toYaml .Values.webhook.securityContext | nindent 12 }}
          image: "{{ .Values.webhook.image.repository }}:{{ .Values.webhook.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.webhook.image.pullPolicy }}
          volumeMounts:
          - name: config-yaml
            mountPath: "/config.yaml"
            subPath: config.yaml
            readOnly: true
          ports:
            - name: http
              containerPort: {{ .Values.webhook.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /api/health
              port: http
          readinessProbe:
            httpGet:
              path: /api/health
              port: http
          resources:
            {{- toYaml .Values.webhook.resources | nindent 12 }}
      {{- if .Values.webhook.configuration.existingSecret }}
      volumes:
      - name: config-yaml
        secret:
          secretName: {{ .Values.webhook.configuration.existingSecret }}
      {{- else }}
      volumes:
      - name: config-yaml
        configMap:
          name: {{ include "yuta.fullname" . }}-webhook
      {{- end}}
      {{- with .Values.webhook.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.webhook.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
