apiVersion: v1
kind: Service
metadata:
  name: {{ include "docker-mailserver.fullname" . }}
  labels:
    {{- include "docker-mailserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: transfer
      port: 25
      targetPort: transfer
      protocol: TCP
    - name: esmtp-implicit
      port: 465
      targetPort: esmtp-implicit
      protocol: TCP
    - name: esmtp-explicit
      port: 587
      targetPort: esmtp-explicit
      protocol: TCP
    - name: imap-implicit
      port: 993
      targetPort: imap-implicit
      protocol: TCP
    - name: imap-explicit
      port: 143
      targetPort: imap-explicit
      protocol: TCP
  selector:
    {{- include "docker-mailserver.selectorLabels" . | nindent 4 }}
