nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  name: ""

core:
  enabled: true
  replicaCount: 1

  image:
    repository: locmai/yuta-core
    tag: ""

  imagePullSecrets: []


  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 8500

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  configuration:
    existingSecret: ""
    server:
      host: "0.0.0.0"
      port: "8500"
      timeout: 15

    jetstream:
      addresses: 
      - "yutaops-nats:4222"
      topic_prefix: "Yuta"

    metrics:
      enabled: false

    tracing:
      enabled: false

    logging:
      - type: "stdout"
        level: "DEBUG"
      
    appservices:
    - type: "kubeops"
      auth: "in-cluster"

messaging:
  enabled: true
  replicaCount: 1

  image:
    repository: locmai/yuta-messaging
    tag: ""

  imagePullSecrets: []

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 8000

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  configuration:
    existingSecret: ""
    server:
      host: "0.0.0.0"
      port: "8000"
      timeout: 15


    jetstream:
      addresses: 
      - "yutaops-nats:4222"
      topic_prefix: "Yuta"

    metrics:
      enabled: true

    tracing:
      enabled: false

    logging:
      - type: "stdout"
        level: "DEBUG"


    chatClients:
      - username: "yuta"
        password: "verystronkpassword"
        homeserverurl: "dendrite.maibaloc.com"
        type: "matrix"

    nluClients:
      - projectid: "yuta-seig"
        languagecode: "en-US"
        type: "diaglogflow"

webhook:
  enabled: true
  replicaCount: 1

  image:
    repository: locmai/yuta-webhook
    tag: ""

  imagePullSecrets: []

  podAnnotations: {}

  podSecurityContext: {}

  securityContext: {}

  service:
    type: ClusterIP
    port: 8501

  resources: {}

  nodeSelector: {}

  tolerations: []

  affinity: {}

  configuration:
    existingSecret: ""
    server:
      host: "0.0.0.0"
      port: "8501"
      timeout: 15


    jetstream:
      addresses: 
      - "yutaops-nats:4222"
      topic_prefix: "Yuta"

    metrics:
      enabled: true

    tracing:
      enabled: false

    logging:
      - type: "stdout"
        level: "DEBUG"


    chatClients:
      - username: "yuta"
        password: "verystronkpassword"
        homeserverurl: "dendrite.maibaloc.com"
        type: "matrix"

    nluClients:
      - projectid: "yuta-seig"
        languagecode: "en-US"
        type: "diaglogflow"

temporary:
  googleauth: true

nats:
  enabled: true

  nats:
    jetstream:
      enabled: true
