apiVersion: v1
name: dendrite
version: 0.0.4
description: Dendrite Matrix Homeserver
type: application
keywords:
  - matrix
  - chat
  - homeserver
  - dendrite
home: https://github.com/matrix-org/dendrite
sources:
  - https://github.com/matrix-org/dendrite
appVersion: 0.0.1

dependencies:
- name: nats
  version: 0.19.5
  repository: https://nats-io.github.io/k8s/helm/charts
  condition: nats.enabled
- name: postgresql
  version: 12.1.9
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
