apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "o-an-quan.fullname" . }}-be
  labels:
    {{- include "o-an-quan.labels" . | nindent 4 }}
    component: backend
spec:
{{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "o-an-quan.selectorLabels" . | nindent 6 }}
      component: backend
  template:
    metadata:
    {{- with .Values.backend.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "o-an-quan.selectorLabels" . | nindent 8 }}
        component: backend
    spec:
      {{- with .Values.backend.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.backend.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.backend.securityContext | nindent 12 }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
          env:
          - name: REACT_APP_BASE_URL
            value: "{{ .Values.backend.baseurl }}"
          - name: REACT_APP_SOCKET_URL
            value: "{{ .Values.backend.socketurl }}"
          - name: REACT_APP_SOCKET_PORT
            value: "{{ .Values.backend.socketport }}"
          ports:
            - name: http
              containerPort: 3003
              protocol: TCP
          resources:
            {{- toYaml .Values.backend.resources | nindent 12 }}
      {{- with .Values.backend.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.backend.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
