apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "neb.fullname" . }}
  labels:
    {{- include "neb.labels" . | nindent 4 }}
data:
  config.yaml: |      
    # Full sample: https://github.com/matrix-org/go-neb/blob/master/config.sample.yaml
    # Go-NEB Configuration File
    clients:
      - UserID: "@goneb:localhost"
        AccessToken: "MDASDASJDIASDJASDAFGFRGER"
        DeviceID: "DEVICE1"
        HomeserverURL: "http://localhost:8008"
        Sync: true
        AutoJoinRooms: true
        DisplayName: "Go-NEB!"
        AcceptVerificationFromUsers: [":localhost:8008"]

    services:
      - ID: "alertmanager_service"
        Type: "alertmanager"
        UserID: "@alertmanager:localhost"
        Config:
          # This is for information purposes only. It should point to Go-NEB path as follows:
          # `/services/hooks/<base64 encoded service ID>`
          # Where in this case "service ID" is "alertmanager_service"
          # Make sure your BASE_URL can be accessed by the Alertmanager instance!
          webhook_url: "http://localhost/services/hooks/YWxlcnRtYW5hZ2VyX3NlcnZpY2U"
          # Each room will get the notification with the alert rendered with the given template
          rooms:
            "!someroomid:domain.tld":
              text_template: "{{range .Alerts -}} [{{ .Status }}] {{index .Labels \"alertname\" }}: {{index .Annotations \"description\"}} {{ end -}}"
              html_template: "{{range .Alerts -}}  {{ $severity := index .Labels \"severity\" }}    {{ if eq .Status \"firing\" }}      {{ if eq $severity \"critical\"}}        <font color='red'><b>[FIRING - CRITICAL]</b></font>      {{ else if eq $severity \"warning\"}}        <font color='orange'><b>[FIRING - WARNING]</b></font>      {{ else }}        <b>[FIRING - {{ $severity }}]</b>      {{ end }}    {{ else }}      <font color='green'><b>[RESOLVED]</b></font>    {{ end }}  {{ index .Labels \"alertname\"}} : {{ index .Annotations \"description\"}}   <a href=\"{{ .GeneratorURL }}\">source</a><br/>{{end -}}"
              msg_type: "m.text"  # Must be either `m.text` or `m.notice`
