apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-generator
  namespace: {{ .Release.Namespace }}
data:
  {{- with .Values.config }}
  configmap.yaml: >
  {{- toYaml . | nindent 4 }}  
  {{- end }}
{{ (.Files.Glob "files/secret-generator/*").AsConfig | indent 2 }}
