on:
  release:
    types: [published, edited]

env:
  RELEASE_TAG: ${{ github.ref_name }}

name: publish-helm-chart 

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Echo ref_name
        run: |
          echo ${{ env.RELEASE_TAG }}


